/*
 * Copyright © 2024-2026 Lolaf.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lolaf.staffix.stores.messages.jdbc;

import lombok.Builder;
import lombok.Getter;
import org.lolaf.staffix.api.msg.MessageType;
import org.lolaf.staffix.api.stores.FixMessagesStoreSettings;

import javax.sql.DataSource;
import java.nio.ByteBuffer;
import java.time.Duration;
import java.util.concurrent.ScheduledExecutorService;
import java.util.function.BiPredicate;

/**
 * The data source and table prefix the JDBC store uses. The schema itself is generated by the DDL plugin.
 */
@Getter
@Builder(toBuilder = true)
public class JdbcMessageStoreSettings implements FixMessagesStoreSettings {

    /**
     * Names this instance, so a session can select it by id when more than one is configured.
     */
    @Builder.Default
    private final String instanceId = DEFAULT_INSTANCE_ID;

    /**
     * DataSource for database access.
     * This should be configured with the appropriate connection pooling.
     */
    private final DataSource dataSource;

    /**
     * Optional table name prefix for multi-tenant scenarios.
     * If not specified, default table name "fix_messages" will be used.
     */
    @Builder.Default
    private final String tablePrefix = "";

    /**
     * Message filter to determine which messages should be stored.
     * By default, all messages are stored.
     */
    @Builder.Default
    private final BiPredicate<MessageType, ByteBuffer> messageFilter = (messageType, message) -> false;

    /**
     * Optional ScheduledExecutorService for asynchronous messages pruning tasks.
     * If not provided, an embedded executor will be created.
     */
    private final ScheduledExecutorService scheduledExecutorService;

    /**
     * Maximum number of messages per session to retain.
     * When the message count exceeds this threshold, pruning will delete
     * the oldest messages to bring the total back down to this limit.
     * Set to 0 to disable pruning.
     * Example: If maxMessagesPerSession=100 and there are 150 messages,
     * pruning will delete the oldest 50 messages, keeping messages 51-150.
     */
    @Builder.Default
    private final int maxMessagesPerSession = 0;

    /**
     * Interval between pruning checks.
     * Default 5 minutes.
     */
    @Builder.Default
    private final Duration pruningCheckInterval = Duration.ofMinutes(5);

    public static class Factory implements FixMessagesStoreFactory<JdbcMessageStoreSettings> {
        @Override
        public Class<JdbcMessageStoreSettings> getSettingsClass() {
            return JdbcMessageStoreSettings.class;
        }

        @Override
        public JdbcMessagesStore newInstance(JdbcMessageStoreSettings settings) {
            return new JdbcMessagesStore(settings);
        }
    }
}
