/*
 * Copyright © 2024-2026 Lolaf.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lolaf.staffix.tests;

import org.lolaf.staffix.api.fields.CoreFields;
import org.lolaf.staffix.api.fields.FixField;
import org.lolaf.staffix.api.msg.MessageType;

import org.lolaf.staffix.api.version.FixVersion;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Minimal raw FIX client for tests: exchanges hand-crafted FIX messages with an acceptor over a plain socket. Used to
 * assert on-the-wire behavior with full control over the fields sent (arbitrary MsgSeqNum(34), PossDupFlag(43), ...)
 * without relying on a full initiator session whose own session-layer handling would hide or rewrite the message.
 * <p>
 * Preferred usage is {@link #connect(int, FixVersion, String, String, Duration)} which pins the FIX version and
 * the sender/target comp ids for the whole conversation, then {@link Session#message(String, long)} builds messages
 * with those defaults (and a current SendingTime(52)) already filled in:
 * <pre>{@code
 * try (Session session = RawFixSocketClient.connect(port, VERSION_44, "SENDER", "TARGET", timeout)) {
 *     session.send(session.message(Logon, 1).set(EncryptMethod.get(), "0").set(HeartBtInt.get(), "5"));
 *     session.send(session.message(TestRequest, 2).set(TestReqID.get(), "hello"));
 * }
 * }</pre>
 * The low-level {@link #fixMessage(String, String...)} / {@link #exchange(int, byte[], Duration)} helpers remain for
 * single-shot exchanges and for building deliberately malformed messages.
 */
public final class RawFixSocketClient {

    private static final DateTimeFormatter SENDING_TIME_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMdd-HH:mm:ss.SSS").withZone(ZoneOffset.UTC);

    private RawFixSocketClient() {
    }

    /**
     * Assembles a FIX message from the given body fields, computing BodyLength(9) and CheckSum(10). Low-level escape
     * hatch: prefer {@link Session#message(String, long)} for well-formed messages.
     *
     * @param beginString the BeginString(8) value, e.g. {@code FIX.4.4} or {@code FIXT.1.1}
     * @param bodyFields  the body fields in order, each as {@code tag=value} (e.g. {@code 35=A}), excluding 8/9/10
     */
    public static byte[] fixMessage(String beginString, String... bodyFields) {
        StringBuilder bodyBuilder = new StringBuilder();
        for (String field : bodyFields) {
            bodyBuilder.append(field).append(CoreFields.FIELD_SEPARATOR);
        }
        String body = bodyBuilder.toString();
        int bodyLength = body.getBytes(StandardCharsets.US_ASCII).length;
        String headAndBody = "8=" + beginString + CoreFields.FIELD_SEPARATOR + "9=" + bodyLength + CoreFields.FIELD_SEPARATOR + body;
        int sum = 0;
        for (byte b : headAndBody.getBytes(StandardCharsets.US_ASCII)) {
            sum += (b & 0xFF);
        }
        String checksum = String.format("%03d", sum % 256);
        return (headAndBody + "10=" + checksum + CoreFields.FIELD_SEPARATOR).getBytes(StandardCharsets.US_ASCII);
    }

    /**
     * Splits a buffer holding several consecutive FIX messages into the individual messages, so that each can be
     * asserted on its own instead of searching the whole buffer. A trailing incomplete message is ignored.
     */
    /**
     * The value of the given field in the given message, for the values a test cannot know in advance, such as the
     * TestReqID(112) of a TestRequest the peer generated by itself.
     *
     * @throws AssertionError if the message does not carry the field
     */
    public static String fieldValue(String message, FixField field) {
        List<String> values = FixMessageFields.valuesOf(message, field.getCode());
        if (values.isEmpty()) {
            throw new AssertionError("No " + field.getClass().getSimpleName() + "(" + field.getCode()
                    + ") field in message: " + message);
        }
        return values.get(0);
    }

    public static List<String> splitMessages(String buffer) {
        String checksumDelimiter = "" + CoreFields.FIELD_SEPARATOR + CoreFields.CHECKSUM + "=";
        List<String> messages = new ArrayList<>();
        int start = 0;
        while (true) {
            int checksumIndex = buffer.indexOf(checksumDelimiter, start);
            if (checksumIndex < 0) {
                return messages;
            }
            int messageEnd = buffer.indexOf(CoreFields.FIELD_SEPARATOR, checksumIndex + checksumDelimiter.length());
            if (messageEnd < 0) {
                return messages;
            }
            messages.add(buffer.substring(start, messageEnd + 1));
            start = messageEnd + 1;
        }
    }

    /**
     * Formats an {@code Instant} as a FIX SendingTime(52) / OrigSendingTime(122) UTC timestamp.
     */
    public static String utcTimestamp(Instant instant) {
        return SENDING_TIME_FORMAT.format(instant);
    }

    /**
     * Sends the request and returns everything read back until a complete message (a CheckSum field) is seen or the
     * timeout elapses.
     */
    public static String exchange(int port, byte[] request, Duration timeout) throws IOException {
        try (Session session = connect(port, timeout)) {
            session.send(request);
            return session.readMessage(timeout);
        }
    }

    /**
     * Opens a stateful raw FIX connection with no message-building context. The caller drives the conversation with
     * {@link Session#send(byte[])} / {@link Session#readMessage(Duration)} and must close it.
     */
    public static Session connect(int port, Duration connectTimeout) throws IOException {
        return connect(port, null, null, null, connectTimeout);
    }

    /**
     * Opens a stateful raw FIX connection that pins the FIX version and the sender/target comp ids used by
     * {@link Session#message(String, long)}.
     */
    public static Session connect(int port, FixVersion version, String senderCompId, String targetCompId,
                                  Duration connectTimeout) throws IOException {
        Socket socket = new Socket();
        socket.connect(new InetSocketAddress("localhost", port), (int) connectTimeout.toMillis());
        String beginString = version != null ? new String(version.getBeginString(), StandardCharsets.US_ASCII) : null;
        return new Session(socket, beginString, senderCompId, targetCompId);
    }

    /**
     * A stateful raw FIX connection. Not thread safe; intended to be driven by a single test thread.
     */
    public static final class Session implements AutoCloseable {

        private final Socket socket;
        private final String beginString;
        private final String senderCompId;
        private final String targetCompId;
        private final ByteArrayOutputStream pending = new ByteArrayOutputStream();

        private Session(Socket socket, String beginString, String senderCompId, String targetCompId) {
            this.socket = socket;
            this.beginString = beginString;
            this.senderCompId = senderCompId;
            this.targetCompId = targetCompId;
        }

        /**
         * Starts building a message of the given MsgType(35) and MsgSeqNum(34). The connection's BeginString(8),
         * SenderCompID(49) and TargetCompID(56) and a current SendingTime(52) are pre-filled; every default can be
         * overridden and any extra field added on the returned {@link Message}.
         */
        public Message message(MessageType messageType, long seqNum) {
            return message(messageType.code(), seqNum);
        }

        public Message message(String msgType, long seqNum) {
            if (beginString == null) {
                throw new IllegalStateException("message(...) requires a connection opened with a FixVersion and comp ids");
            }
            return new Message(msgType, seqNum);
        }

        public void send(Message message) throws IOException {
            send(message.build());
        }

        public void send(byte[] message) throws IOException {
            socket.getOutputStream().write(message);
            socket.getOutputStream().flush();
        }

        /**
         * Reads until one complete FIX message (delimited by a CheckSum(10) field) has been received or the timeout
         * elapses. Any bytes read beyond that message are buffered and returned by the next call.
         *
         * @return the raw bytes of the next message, or whatever was buffered/read when the timeout elapsed
         */
        public String readMessage(Duration timeout) throws IOException {
            String checksumDelimiter = "" + CoreFields.FIELD_SEPARATOR + CoreFields.CHECKSUM + "=";
            long deadline = System.currentTimeMillis() + timeout.toMillis();
            socket.setSoTimeout(Math.max(1, (int) timeout.toMillis()));
            byte[] buffer = new byte[4096];
            while (true) {
                String current = pending.toString(StandardCharsets.US_ASCII);
                int checksumIndex = current.indexOf(checksumDelimiter);
                if (checksumIndex >= 0) {
                    // a full message ends at the SOH following the 3-digit checksum value
                    int messageEnd = current.indexOf(CoreFields.FIELD_SEPARATOR, checksumIndex + checksumDelimiter.length());
                    if (messageEnd >= 0) {
                        int cut = messageEnd + 1;
                        String message = current.substring(0, cut);
                        byte[] remainder = current.substring(cut).getBytes(StandardCharsets.US_ASCII);
                        pending.reset();
                        pending.write(remainder, 0, remainder.length);
                        return message;
                    }
                }
                if (System.currentTimeMillis() >= deadline) {
                    return current;
                }
                int read;
                try {
                    read = socket.getInputStream().read(buffer);
                } catch (SocketTimeoutException timeoutException) {
                    return pending.toString(StandardCharsets.US_ASCII);
                }
                if (read < 0) {
                    return pending.toString(StandardCharsets.US_ASCII);
                }
                pending.write(buffer, 0, read);
            }
        }

        /**
         * Reads messages until one carrying the given field with the given value is received, or the timeout elapses.
         * The match is on the field, not on a substring of the wire format, so looking for SessionRejectReason(373)
         * {@code 1} does not stop on a message carrying {@code 373=10}.
         *
         * @return the matching message, or whatever the last read returned when the timeout elapsed, which is an
         * empty string once nothing more arrives
         */
        public String readMessageWithField(FixField field, String value, Duration timeout) throws IOException {
            return readMessageWithField(field.getCode(), value, timeout);
        }

        /**
         * Reads messages until one of the given MsgType(35) is received, or the timeout elapses.
         *
         * @return the matching message, or whatever the last read returned when the timeout elapsed, which is an
         * empty string once nothing more arrives
         */
        public String readMessageOfType(MessageType messageType, Duration timeout) throws IOException {
            return readMessageWithField(CoreFields.MESSAGE_TYPE, messageType.code(), timeout);
        }

        private String readMessageWithField(int tag, String value, Duration timeout) throws IOException {
            String message = "";
            long deadline = System.currentTimeMillis() + timeout.toMillis();
            while (!FixMessageFields.hasFieldWithValue(message, tag, value) && System.currentTimeMillis() < deadline) {
                message = readMessage(timeout);
            }
            return message;
        }

        /**
         * Waits for the peer to close the connection, discarding any bytes received in the meantime (e.g. a heartbeat
         * sent between a Logout and the disconnect).
         *
         * @return {@code true} if end of stream is reached within the timeout, {@code false} otherwise
         */
        public boolean isClosedByPeer(Duration timeout) throws IOException {
            long deadline = System.currentTimeMillis() + timeout.toMillis();
            byte[] buffer = new byte[4096];
            while (System.currentTimeMillis() < deadline) {
                socket.setSoTimeout(Math.max(1, (int) (deadline - System.currentTimeMillis())));
                try {
                    if (socket.getInputStream().read(buffer) < 0) {
                        return true;
                    }
                    // otherwise data (e.g. a heartbeat) arrived, discard it and keep waiting for the close
                } catch (SocketTimeoutException timeoutException) {
                    return false;
                }
            }
            return false;
        }

        @Override
        public void close() throws IOException {
            socket.close();
        }

        /**
         * A well-formed FIX message under construction. The header (BeginString, BodyLength, MsgType, MsgSeqNum,
         * SenderCompID, TargetCompID, SendingTime) is emitted in canonical order; {@link #set} appends extra fields
         * after SendingTime; BodyLength(9) and CheckSum(10) are computed on {@link #build()}.
         */
        public final class Message {

            private final String msgType;
            private final long seqNum;
            private final Map<String, String> extraFields = new LinkedHashMap<>();
            private String sender = senderCompId;
            private String target = targetCompId;
            private Instant sendingTime = Instant.now();
            private Integer declaredBodyLength;

            private Message(String msgType, long seqNum) {
                this.msgType = msgType;
                this.seqNum = seqNum;
            }

            /**
             * Overrides SenderCompID(49).
             */
            public Message senderCompId(String value) {
                this.sender = value;
                return this;
            }

            /**
             * Overrides TargetCompID(56).
             */
            public Message targetCompId(String value) {
                this.target = value;
                return this;
            }

            /**
             * Overrides SendingTime(52).
             */
            public Message sendingTime(Instant value) {
                this.sendingTime = value;
                return this;
            }

            /**
             * Omits SendingTime(52) entirely.
             */
            public Message noSendingTime() {
                this.sendingTime = null;
                return this;
            }

            /**
             * Sets OrigSendingTime(122).
             */
            public Message origSendingTime(Instant value) {
                return set(CoreFields.ORIG_SENDING_TIME, utcTimestamp(value));
            }

            /**
             * Overrides the BodyLength(9) actually advertised, to build a deliberately garbled message. The
             * CheckSum(10) is still computed over the emitted bytes, so BodyLength is the only thing wrong.
             */
            public Message declaredBodyLength(int value) {
                this.declaredBodyLength = value;
                return this;
            }

            /**
             * Sets an arbitrary field by its numeric tag.
             */
            public Message set(int tag, String value) {
                extraFields.put(Integer.toString(tag), value);
                return this;
            }

            /**
             * Sets an arbitrary field, identified by a {@link FixField} (e.g. {@code EncryptMethod.get()}).
             */
            public Message set(FixField field, String value) {
                return set(field.getCode(), value);
            }

            public byte[] build() {
                StringBuilder fields = new StringBuilder();
                appendField(fields, CoreFields.MESSAGE_TYPE, msgType);
                appendField(fields, CoreFields.MESSAGE_SEQ_NUM, Long.toString(seqNum));
                appendField(fields, CoreFields.SENDER_COMP_ID, sender);
                appendField(fields, CoreFields.TARGET_COMP_ID, target);
                if (sendingTime != null) {
                    appendField(fields, CoreFields.SENDING_TIME, utcTimestamp(sendingTime));
                }
                extraFields.forEach((tag, value) -> fields.append(tag).append('=').append(value).append(CoreFields.FIELD_SEPARATOR));

                String body = fields.toString();
                int bodyLength = declaredBodyLength != null ? declaredBodyLength : body.getBytes(StandardCharsets.US_ASCII).length;
                String headAndBody = "8=" + beginString + CoreFields.FIELD_SEPARATOR + "9=" + bodyLength + CoreFields.FIELD_SEPARATOR + body;
                int sum = 0;
                for (byte b : headAndBody.getBytes(StandardCharsets.US_ASCII)) {
                    sum += (b & 0xFF);
                }
                String checksum = String.format("%03d", sum % 256);
                return (headAndBody + "10=" + checksum + CoreFields.FIELD_SEPARATOR).getBytes(StandardCharsets.US_ASCII);
            }

            private void appendField(StringBuilder fields, int tag, String value) {
                fields.append(tag).append('=').append(value).append(CoreFields.FIELD_SEPARATOR);
            }
        }
    }
}
