<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.lolaf.staffix</groupId>
        <artifactId>staffix-monitoring-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>

    <name>Staffix Micrometer OTLP Monitoring (Parent)</name>
    <description>
        The OTLP meter registry and its Spring Boot auto-configuration.
    </description>

    <artifactId>staffix-monitoring-micrometer-otlp-parent</artifactId>

    <modules>
        <module>micrometer-otlp-impl</module>
        <module>micrometer-otlp-spring-boot</module>
    </modules>

</project>
