/*
 * Copyright © 2024-2026 Lolaf.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lolaf.staffix.sessions.settings.document;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.lolaf.staffix.api.version.FixRegularVersion;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class TestFixSessionSettingsJsonSchema {

    /**
     * The module's directory is the working directory of a Maven test run.
     */
    private static final List<Path> SOURCE_ROOTS = List.of(Path.of("../../api/src/main/java"), Path.of("src/main/java"));

    private static byte[] readAll(InputStream stream) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] chunk = new byte[8192];
        int read;
        while ((read = stream.read(chunk)) != -1) {
            buffer.write(chunk, 0, read);
        }
        return buffer.toByteArray();
    }

    @Test
    void packagedSchemaMatchesTheModel() throws IOException {
        String packaged;
        try (InputStream stream = FixSessionSettingsJsonSchema.openPackagedSchema()) {
            assertThat(stream)
                    .describedAs("schema packaged in the jar (generated by exec-maven-plugin at process-classes; "
                            + "run `mvn process-classes` if this fails in an IDE that compiled without Maven)")
                    .isNotNull();
            packaged = new String(readAll(stream), StandardCharsets.UTF_8);
        }

        assertThat(packaged)
                .describedAs("packaged schema must match the model it is generated from")
                .isEqualTo(generateSchema());
    }

    private static String generateSchema() throws IOException {
        return FixSessionSettingsJsonSchemaGenerator.generate(SOURCE_ROOTS);
    }

    @Test
    void packagedResolvedSchemaMatchesTheModelWithoutPlaceholders() throws IOException {
        String packaged;
        try (InputStream stream = FixSessionSettingsJsonSchema.openPackagedResolvedSchema()) {
            assertThat(stream).isNotNull();
            packaged = new String(readAll(stream), StandardCharsets.UTF_8);
        }

        assertThat(packaged).isEqualTo(FixSessionSettingsJsonSchemaGenerator.generateResolved(SOURCE_ROOTS));
        JsonNode duration = new ObjectMapper().readTree(packaged).path("properties").path("logInOrOutResponseTimeout");
        assertThat(duration.has("anyOf")).isFalse();
        assertThat(duration.path("format").asText()).isEqualTo("duration");
        assertThat(duration.path("description").asText()).startsWith("How long a Logon or Logout");
    }

    @Test
    void valuesWrittenAsStringsAreDescribedAsStrings() throws IOException {
        JsonNode properties = new ObjectMapper().readTree(FixSessionSettingsJsonSchemaGenerator.generateResolved(SOURCE_ROOTS))
                .path("properties");

        assertThat(properties.at("/allowedAddresses/items/type").asText()).isEqualTo("string");
        assertThat(properties.at("/sessionScheduleSettings/properties/timeZone/type").asText()).isEqualTo("string");
    }

    @Test
    void theFixVersionsListedAreTheOnesReadBack() throws IOException {
        JsonNode versions = new ObjectMapper().readTree(FixSessionSettingsJsonSchemaGenerator.generateResolved(SOURCE_ROOTS))
                .at("/properties/fixSessionId/properties/fixVersion/enum");

        assertThat(versions).isNotEmpty();
        versions.forEach(version -> assertThat(FixRegularVersion.fromString(version.asText())).as(version.asText()).isPresent());
    }

    @Test
    void everyPropertyIsDescribed() throws IOException {
        JsonNode schema = new ObjectMapper().readTree(generateSchema());

        assertThat(undescribedProperties(schema, ""))
                .describedAs("each needs javadoc on the FixSessionSettings field of the same name, or on the "
                        + "FixSessionSettingsDocument field when only a document has it")
                .isEmpty();
    }

    private static List<String> undescribedProperties(JsonNode objectSchema, String path) {
        List<String> undescribed = new ArrayList<>();
        objectSchema.path("properties").fields().forEachRemaining(property -> {
            String propertyPath = path + property.getKey();
            if (!property.getValue().hasNonNull("description")) {
                undescribed.add(propertyPath);
            }
            undescribed.addAll(undescribedProperties(property.getValue(), propertyPath + "."));
            undescribed.addAll(undescribedProperties(property.getValue().path("items"), propertyPath + "[]."));
        });
        return undescribed;
    }

    @Test
    void descriptionsAreTheSettingsJavadocAsPlainText() throws IOException {
        JsonNode properties = new ObjectMapper().readTree(generateSchema()).path("properties");

        assertThat(properties.path("logInOrOutResponseTimeout").path("description").asText())
                .isEqualTo("How long a Logon or Logout may go unanswered before the connection is dropped.");
        assertThat(properties.path("desiredSessionState").path("description").asText())
                .startsWith("The state the session holds itself in. FixSessionState.LOGGED_IN by default")
                .doesNotContain("{@link");
        assertThat(properties.path("heartBeatInterval").path("description").asText())
                .startsWith("HeartBtInt(108): how often a quiet session proves it is alive")
                .contains("\n\nAn initiator proposes it at Logon")
                .doesNotContain("<p>");
    }

    @Test
    void defaultsAreThoseOfSettingsBuiltWithNothingSet() throws IOException {
        JsonNode properties = new ObjectMapper().readTree(generateSchema()).path("properties");

        assertThat(properties.path("logInOrOutResponseTimeout").path("default").asText()).isEqualTo("PT10S");
        assertThat(properties.path("heartBeatInterval").path("properties").path("initiatorInterval").path("default").asText())
                .isEqualTo("PT10S");
        assertThat(properties.path("desiredSessionState").path("default").asText()).isEqualTo("LOGGED_IN");
        assertThat(properties.path("fixSessionType").has("default")).isFalse();
        assertThat(properties.path("sessionScheduleSettings").path("properties").path("timeZone").has("default")).isFalse();
    }

    @Test
    void generatedSchemaDescribesTheModel() throws IOException {
        String schemaJson = generateSchema();

        JsonNode schema = new ObjectMapper().readTree(schemaJson);
        assertThat(schema.get("$schema").asText()).contains("2020-12");
        assertThat(schema.get("properties").has("fixSessionId")).isTrue();
        assertThat(schema.get("required")).isNotNull();
        assertThat(schema.get("required").toString()).contains("fixSessionId");
    }

    @Test
    void durationFieldsAreConstrainedByPattern() throws IOException {
        JsonNode schema = new ObjectMapper().readTree(generateSchema());

        // The declared type is the first anyOf branch; the second lets a ${...} placeholder stand here.
        JsonNode duration = schema.get("properties").get("logInOrOutResponseTimeout").get("anyOf").get(0);
        assertThat(duration.get("type").asText()).isEqualTo("string");
        assertThat(duration.get("format").asText()).isEqualTo("duration");
        assertThat(duration.has("pattern")).isTrue();

        String pattern = duration.get("pattern").asText();
        assertThat("PT0.0000015S").matches(pattern);
        assertThat("10s").doesNotMatch(pattern);
        assertThat("P1Y").doesNotMatch(pattern);
    }

    @Test
    void scheduleTimesAreConstrainedByLocalTimePattern() throws IOException {
        JsonNode schema = new ObjectMapper().readTree(generateSchema());

        JsonNode startTime = schema.path("properties").path("sessionScheduleSettings")
                .path("properties").path("sessionSchedules")
                .path("items").path("properties").path("startTime").path("anyOf").path(0);
        assertThat(startTime.get("type").asText()).isEqualTo("string");
        assertThat(startTime.has("pattern")).isTrue();

        String pattern = startTime.get("pattern").asText();
        assertThat("10:10:10.099999999").matches(pattern);
        assertThat("09:30").matches(pattern);
        assertThat("25:00").doesNotMatch(pattern);
        assertThat("10:10:11Z").doesNotMatch(pattern);
    }

    /**
     * Every non-enum scalar also accepts a placeholder, so an editor does not flag one standing in a
     * typed field. Enums keep their exact declaration.
     */
    @Test
    void nonEnumScalarsAlsoAcceptAPlaceholder() throws IOException {
        JsonNode schema = new ObjectMapper().readTree(generateSchema());

        JsonNode duration = schema.path("properties").path("logInOrOutResponseTimeout");
        assertThat(duration.has("anyOf")).isTrue();
        String placeholderPattern = duration.path("anyOf").path(1).path("pattern").asText();
        assertThat("${sysprop:x:PT30S}").matches(placeholderPattern);
        assertThat("prefix-${env:X}-suffix").matches(placeholderPattern);
        assertThat("PT30S").doesNotMatch(placeholderPattern);

        JsonNode sessionType = schema.path("properties").path("fixSessionType");
        assertThat(sessionType.has("anyOf")).isFalse();
        assertThat(sessionType.has("enum")).isTrue();
    }
}
