<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.lolaf.staffix</groupId>
        <artifactId>staffix-messages-logger-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>

    <name>Staffix OTLP Message Logger (Parent)</name>
    <description>
        The OTLP message logger and its Spring Boot auto-configuration.
    </description>

    <artifactId>staffix-messages-logger-otlp-parent</artifactId>

    <modules>
        <module>otlp-impl</module>
        <module>otlp-spring-boot</module>
    </modules>

</project>
