/*
 * Copyright © 2024-2026 Lolaf.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lolaf.staffix.api.msg;

import lombok.experimental.UtilityClass;
import lombok.extern.slf4j.Slf4j;
import org.lolaf.staffix.api.FixDictionaryId;

import java.util.Collection;
import java.util.List;
import java.util.ServiceLoader;
import java.util.stream.Collectors;

/**
 * Every MsgType(35) a dictionary defines, looked up by code or by the hash of one.
 *
 * <p>The hash overload is the one the parser uses: it identifies the message type without building a String for
 * the two or three bytes of tag 35. Instances come from the generated FIX packages through
 * {@link java.util.ServiceLoader}, keyed by {@link org.lolaf.staffix.api.FixDictionaryId}.
 */
public interface MessageTypeRegistry {

    FixDictionaryId getTargetDictionary();

    /**
     * Find a message type instance
     *
     * @param messageType the message type string
     * @return a singleton instance for the given messageType or null if the registry does not have such message
     */
    MessageType find(String messageType);

    /**
     * Find a message type using a message type String hash generated by {@link org.lolaf.staffix.api.serde.Hashing#hash(String)}
     */
    MessageType find(int messageTypeHash);

    Collection<MessageType> getMessageTypes();

    @Slf4j
    @UtilityClass
    class Registry {

        private static final Collection<MessageTypeRegistry> SPI_INSTANCES = loadInstances();

        public static MessageTypeRegistry getInstance(FixDictionaryId fixDictionaryId) {
            return SPI_INSTANCES.stream().filter(r -> r.getTargetDictionary().equals(fixDictionaryId)).findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("Unable to find any MessageTypeRegistry SPI instance for dictionary " + fixDictionaryId));
        }

        private static Collection<MessageTypeRegistry> loadInstances() {
            List<MessageTypeRegistry> instances = ServiceLoader.load(MessageTypeRegistry.class)
                    .stream().map(ServiceLoader.Provider::get).collect(Collectors.toList());
            log.info("Loaded MessageTypeRegistry SPI instances for dictionaries: {}", instances.stream().map(MessageTypeRegistry::getTargetDictionary).collect(Collectors.toList()));
            return instances;
        }
    }
}