name: build

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    uses: lolaf-org/workflows/.github/workflows/maven-build.yml@v1.0.2
    with:
      timeout-minutes: 60
